### ISSUE TITLE
About the feature extraction

### ISSUE THREAD

**Issue by rookiecm** [doc-doc/vRGV#10]
Hi, when i run `./detection.sh` to extract features, I have obtain discontinuous results. For example, there are 560 frames in ILSVRC2015 train 00008004. However, only 512 .pkl files are extracted with the rest missed. Could you please offer some advice?
![image](https://user-images.githubusercontent.com/32630698/99925080-9c34db80-2d77-11eb-82fe-6325a4a781ff.png)

**Comment by doc-doc** [comment]
Hi, that's normal, because I sampled 512 frames for each video, and finally 120 were used.  Please refer to dataloader/detect_frame_loader:get_frames()

**Comment by rookiecm** [comment]
Thanks for your kind reply. I have another question. Should Line 52 in dataloader/util.py ` samples = np.round(np.linspace(1, nframe, sample_num))` be changed to `samples = np.round(np.linspace(0, nframe-1, sample_num))` since the frame index starts from 0.

**Comment by doc-doc** [comment]
Yes, please change back to np.linspace(0, nframe-1, sample_num), the code has been changed a bit after the submission.

**Comment by rookiecm** [comment]
Got it. Thank you for your patience and prompt reply.

**Comment by rookiecm** [comment]
Sorry, I have another problem. When I have extracted the features and merge both the training and validation sets into one directory `../ground_data/vidvrd/frame_feature`, the `./ground.sh 0 train ` command raise one error that some .pkl file is not find. I think this is due to different sampling strategies at detection and training stages:  in detection, dataloader/util.py: `samples = np.round(np.linspace(0, nframe-1, sample_num))` with sample_num = 512, while in training, dataloader/ground_loader.py: get_video_feature() `sample_frames = np.round(np.linspace(0, frame_count - 1, self.frame_steps))`, here self.frame_steps = 120. Not all the sampled frames are pre-extracted before. Could you please offer some advice?

**Comment by doc-doc** [comment]
I found that I extracted features for all frames for this dataset. If you do not mind to check the missing frames and get their features back (recommended), or you can change the numer 512 (in dataloader/util:get_frames()) to 120 and re-extract all features.

**Comment by rookiecm** [comment]
To extract features for all frames, I guess to change  dataloader/util.py: `samples = np.round(np.linspace(0, nframe-1, sample_num))` to `samples = np.round(np.linspace(0, nframe-1, nframe))`  is OK ?

**Comment by doc-doc** [comment]
you can also change to 
```
samples = list(range(nframe))
```
