### ISSUE TITLE
Train Error

### ISSUE THREAD

**Issue by rookiecm** [doc-doc/vRGV#11]
Thanks for sharing the code and I have one problem during training.

When I have extracted the features and merge both the training and validation sets into one directory ../ground_data/vidvrd/frame_feature, the ./ground.sh 0 train command raise one error that some .pkl file is not find. I think this is due to different sampling strategies at detection and training stages: in detection, dataloader/util.py: samples = np.round(np.linspace(0, nframe-1, sample_num)) with sample_num = 512, while in training, dataloader/ground_loader.py: get_video_feature() sample_frames = np.round(np.linspace(0, frame_count - 1, self.frame_steps)), here self.frame_steps = 120. Not all the sampled frames are pre-extracted before. Could you please offer some advice?

**Comment by doc-doc** [comment]
Please change 512 to 120.

**Comment by rookiecm** [comment]
I am quite confused about the `ground_data/vidvrd/video_feature` directory. Could you please explain why you set these cache files and how they are generated ? Thanks !
