### ISSUE TITLE
Inference Error

### ISSUE THREAD

**Issue by rookiecm** [doc-doc/vRGV#12]
When I run `python.py generate_track_link.py` (maybe typo in Readme: generate_track_lick.py), I have the following error `KeyError: 'dog-larger-frisbee'`. I found that this error is raised because that there is 'dog-larger-frisbee' relation in vrelation_val.json file while the inference result do not have this relation. For example,  in ground truth, ILSVRC2015_train_00005004 has three relations "dog-stand_behind-frisbee", "dog-larger-frisbee" and "frisbee-front-dog", while in inference results, it only contains the "dog-stand_behind-frisbee". Could you please offer some advice?

**Comment by doc-doc** [comment]
Hi, please set batch_size to 1 (in this version) during inference.

**Comment by rookiecm** [comment]
Do you mean batch_size in `ground.py` ? Could you explain a little bit more detailedly? I am new to this task and quite confused. Thanks a lot.
