### ISSUE TITLE
Cannot reimplement the result reported in the paper

### ISSUE THREAD

**Issue by Harryqu123** [doc-doc/vRGV#16]
Hi, thanks for your work and this proposed interesting new task.
However, the final result I reimplement following the readme instruction as shown below is far from the reported result in the paper.
Acc_S    Acc_O   Acc_R
8.87     8.74    1.18
As I change some places so that I can run the code, I just want to ask if there are any places that I change wrongly?
Firstly, I do not install bert-score as it shows it is not compatible with torch 0.4.1, can I know where is bert-score used if this is crucial as I don't find its usage
Secondly, during feature extraction, I uncomment self.train() in https://github.com/doc-doc/vRGV/blob/9933694d52307f80ae110cc30fff5232ac4b5e51/dataloader/detect_frame_loader.py#L118 and move the extracted feature from ../ground_data/frame_feature/ to ../ground_data/vidvrd/frame_feature/ based on my understanding in order for me to run the training code successfully. I am not sure whether these two changes are made correctly and if not what changes should I make so that I can run the code successfully.
I don't think I make any other changes besides the above-mentioned two and I get the result which is very low as shown above.
Can I know how should I correct my implementation so that I can get the same result as shown in the paper?
Many thanks

**Comment by doc-doc** [comment]
Hi, thanks for your interest.  The problem has been solved already and sorry that I was travelling overseas and could not receive the verfication code to reply to your question here.

**Comment by Harryqu123** [comment]
Thanks for your reply.
I would try to rerun the code and I would close the issue now.
